"""add_user_id_to_distribution_config_objects

Revision ID: 00004
Revises: 00003
Create Date: 2025-10-27 19:13:47.544604

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00004"
down_revision: Union[str, None] = "00003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("distribution_configs", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "distribution_configs", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "distribution_configs", type_="foreignkey")
    op.drop_column("distribution_configs", "user_id")
    # ### end Alembic commands ###
