"""change_pricing_config_to_one_to_one

Revision ID: 00005
Revises: 00004
Create Date: 2025-11-17 16:24:41.888617

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00005"
down_revision: Union[str, None] = "00004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "pricing_configs", ["reo_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pricing_configs", type_="unique")
    # ### end Alembic commands ###
