"""added is_active to Premises

Revision ID: 00002
Revises: 00001
Create Date: 2025-10-26 16:33:39.138731

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00002"
down_revision: Union[str, None] = "00001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("premises", sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False))
    op.alter_column("premises", "is_active", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("premises", "is_active")
    # ### end Alembic commands ###
