"""Add window_view_attachments table

Revision ID: 00007
Revises: 00006
Create Date: 2026-01-06 15:03:55.439691

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00007"
down_revision: Union[str, None] = "00006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "window_view_attachments",
        sa.Column("reo_id", sa.Integer(), nullable=False),
        sa.Column("view_from_window", sa.String(), nullable=False),
        sa.Column("base64_file", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["reo_id"],
            ["real_estate_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index(
        op.f("ix_window_view_attachments_view_from_window"),
        "window_view_attachments",
        ["view_from_window"],
        unique=False,
    )
    op.drop_constraint(op.f("layout_type_attachments_reo_id_fkey"), "layout_type_attachments", type_="foreignkey")
    op.create_foreign_key(None, "layout_type_attachments", "real_estate_objects", ["reo_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "layout_type_attachments", type_="foreignkey")
    op.create_foreign_key(
        op.f("layout_type_attachments_reo_id_fkey"),
        "layout_type_attachments",
        "real_estate_objects",
        ["reo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_window_view_attachments_view_from_window"), table_name="window_view_attachments")
    op.drop_table("window_view_attachments")
    # ### end Alembic commands ###
