"""add config_status field

Revision ID: 00009
Revises: 00008
Create Date: 2026-02-03 16:30:36.576958

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00009"
down_revision: Union[str, None] = "00008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "distribution_configs",
        sa.Column(
            "config_status",
            sa.Enum("DEFAULT", "CUSTOM", name="configstatus_enum", native_enum=False),
            server_default="CUSTOM",
            nullable=False,
        ),
    )
    op.alter_column("distribution_configs", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("distribution_configs", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("distribution_configs", "config_status")
    # ### end Alembic commands ###
