"""add_property_class_to_real_estate_objects

Revision ID: 00005
Revises: 00004
Create Date: 2025-11-28 15:15:21.999473

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00005"
down_revision: Union[str, None] = "00004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "real_estate_objects",
        sa.Column(
            "property_class",
            sa.Enum("ECONOMY", "COMFORT", "BUSINESS", "PREMIUM", name="propertyclassenum", native_enum=False),
            nullable=True,
        ),
    )

    op.execute("UPDATE real_estate_objects SET property_class = 'ECONOMY' WHERE property_class IS NULL")

    op.alter_column("real_estate_objects", "property_class", nullable=False)

    op.alter_column("real_estate_objects", "curr", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("real_estate_objects", "curr", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("real_estate_objects", "property_class")
    # ### end Alembic commands ###
