"""removed changes

Revision ID: 1c59ae53ec1e
Revises: c87367406820
Create Date: 2025-08-23 17:11:10.336548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c59ae53ec1e'
down_revision: Union[str, Sequence[str], None] = 'c87367406820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_plans', 'file_name')
    op.drop_column('premises', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premises', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('income_plans', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
