"""added filename to premises and plans

Revision ID: c87367406820
Revises: 99571e31d086
Create Date: 2025-08-23 16:11:22.623553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87367406820'
down_revision: Union[str, Sequence[str], None] = '99571e31d086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_plans', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('premises', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premises', 'file_name')
    op.drop_column('income_plans', 'file_name')
    # ### end Alembic commands ###
